const kanji = {
    //https://jsfiddle.net/marquesadilla/hLsv9apu/24/
    tango: {
        'cmd-alt-F7': { 読み方: [''], form: '', 意味: "Show usages" },
        'ctrl-J, F1': { 読み方: [''], form: '', 意味: "Quick Documentation Lookup" },
        'cmd-P': { 読み方: [''], form: '', 意味: "Parameter info (within method call arguments)" },
        'ctrl-space': { 読み方: [''], form: '', 意味: "Code completion" },
        'cmd-cmd': { 読み方: [''], form: '', 意味: "Show/Hide tool window bar" },
        'cmd-shift-F12': { 読み方: [''], form: '', 意味: "Maximize editor window" },
        'cmd-shift-A': { 読み方: [''], form: '', 意味: "Find action by name" },
        'cmd-/': { 読み方: [''], form: '', 意味: "Comment/Uncomment current line with '//'" },
        'cmd-B': { 読み方: [''], form: '', 意味: "Navigate to declaration" },
        'ctrl-alt-l': { 読み方: [''], form: '', 意味: "Fix indentation for current line" },
        'ctrl-right_arrow, ctrl-left_arrow': { 読み方: [''], form: '', 意味: "Navigate in open tabs" },
        'alt-space': { 読み方: [''], form: '', 意味: "Quick Definition" },
        'cmd-e': { 読み方: [''], form: '', 意味: "Recent files" },
        'cmd-F12': { 読み方: [''], form: '', 意味: "File Structure" },
        'ctrl-up_arrow, ctrl-dn_arrow': { 読み方: [''], form: '', 意味: "Next method, previous method" },
        'delete': { 読み方: [''], form: '', 意味: "Backward Delete Char" },
        'fn + delete': { 読み方: [''], form: '', 意味: "Forward Delete Char" },
        'left arrow': { 読み方: [''], form: '', 意味: "Backward Char" },
        'right arrow': { 読み方: [''], form: '', 意味: "Forward Char" },
        'shift + left arrow': { 読み方: [''], form: '', 意味: "Backward Select Char" },
        'shift + right arrow': { 読み方: [''], form: '', 意味: "Forward Select Char" },
        'option + delete': { 読み方: [''], form: '', 意味: "Backward Delete Word" },
        'fn + option + delete': { 読み方: [''], form: '', 意味: "Forward Delete Word" },
        'option + left arrow': { 読み方: [''], form: '', 意味: "Backward Word" },
        'option + right arrow': { 読み方: [''], form: '', 意味: "Forward Word" },
        'shift + option + left arrow': { 読み方: [''], form: '', 意味: "Backward Select Word" },
        'shift + option + right arrow': { 読み方: [''], form: '', 意味: "Forward Select Word" },
        'cmd + D': { 読み方: [''], form: '', 意味: "Duplicate Line" },
        'cmd + delete': { 読み方: [''], form: '', 意味: "Delete Line" },
        'fn + right arrow': { 読み方: [''], form: '', 意味: "End of Line" },
        'fn + left arrow': { 読み方: [''], form: '', 意味: "Beginning of Line" },
        'cmd + shift + dn arrow': { 読み方: [''], form: '', 意味: "Move Line Down" },
        'cmd + shift + up arrow': { 読み方: [''], form: '', 意味: "Move Line Up" },
        // : { 読み方: [''], form: '', 意味: "" },


    },

    yomerebaii: {
        'Show usages': {読み方: [''], form: '', 意味: 'cmd-alt-F7' },
        'Quick Documentation Lookup': {読み方: [''], form: '', 意味: 'ctrl-J, F1' },
        'Parameter info (within method call arguments)': {読み方: [''], form: '', 意味: 'cmd-P' },
        'Code completion': {読み方: [''], form: '', 意味: 'ctrl-space' },
        'Show/Hide tool window bar': {読み方: [''], form: '', 意味: 'cmd-cmd' },
        'Maximize editor window': {読み方: [''], form: '', 意味: 'cmd-shift-F12' },
        'Find action by name': {読み方: [''], form: '', 意味: 'cmd-shift-A' },
        "Comment/Uncomment current line with '//'": {読み方: [''], form: '', 意味: 'cmd-/' },
        'Navigate to declaration': {読み方: [''], form: '', 意味: 'cmd-B' },
        'Fix indentation for current line': {読み方: [''], form: '', 意味: 'ctrl-alt-l' },
        'Navigate in open tabs': {読み方: [''], form: '', 意味: 'ctrl-right_arrow, ctrl-left_arrow' },
        'Quick Definition': {読み方: [''], form: '', 意味: 'alt-space' },
        'Recent files': {読み方: [''], form: '', 意味: 'cmd-e' },
        'File Structure': {読み方: [''], form: '', 意味: 'cmd-F12' },
        'Next method, previous method': {読み方: [''], form: '', 意味: 'ctrl-up_arrow, ctrl-dn_arrow' },
        'Backward Delete Char': {読み方: [''], form: '', 意味: 'delete' },
        'Forward Delete Char': {読み方: [''], form: '', 意味: 'fn + delete' },
        'Backward Char': {読み方: [''], form: '', 意味: 'left arrow' },
        'Forward Char': {読み方: [''], form: '', 意味: 'right arrow' },
        'Backward Select Char': {読み方: [''], form: '', 意味: 'shift + left arrow' },
        'Forward Select Char': {読み方: [''], form: '', 意味: 'shift + right arrow' },
        'Backward Delete Word': {読み方: [''], form: '', 意味: 'option + delete' },
        'Forward Delete Word': {読み方: [''], form: '', 意味: 'fn + option + delete' },
        'Backward Word': {読み方: [''], form: '', 意味: 'option + left arrow' },
        'Forward Word': {読み方: [''], form: '', 意味: 'option + right arrow' },
        'Backward Select Word': {読み方: [''], form: '', 意味: 'shift + option + left arrow' },
        'Forward Select Word': {読み方: [''], form: '', 意味: 'shift + option + right arrow' },
        'Duplicate Line': {読み方: [''], form: '', 意味: 'cmd + D' },
        'Delete Line': {読み方: [''], form: '', 意味: 'cmd + delete' },
        'End of Line': {読み方: [''], form: '', 意味: 'fn + right arrow' },
        'Beginning of Line': {読み方: [''], form: '', 意味: 'fn + left arrow' },
        'Move Line Down': {読み方: [''], form: '', 意味: 'cmd + shift + dn arrow' },
        'Move Line Up': {読み方: [''], form: '', 意味: 'cmd + shift + up arrow' },
    }
}

export default kanji;   